import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

interface QuoteData {
    projectName: string;
    clientName: string;
    date: string;
    signatureData?: string;
    specs: {
        length: string;
        width: string;
        layers: any[];
    };
    language?: 'en' | 'de';
    results: {
        area: string;
        tonnage: number;
        pricePerTon: string;
        totalCost: string;
    };
}

export function generateQuote(data: QuoteData) {
    const doc = new jsPDF();

    // --- Branding / Header ---
    doc.setFillColor(245, 158, 11); // Amber-500
    doc.rect(0, 0, 210, 45, "F");

    doc.setTextColor(0, 0, 0);
    doc.setFontSize(28);
    doc.setFont("helvetica", "bold");
    doc.text("Smart Field", 20, 22);

    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(50, 50, 50);
    doc.text("Made by Mehdi Lakhouane", 20, 38);

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(0, 0, 0);
    doc.text(`Date: ${data.date}`, 150, 22);

    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.text("Professional Asphalt Calculator", 20, 30);

    // --- Client / Project Info ---
    doc.setDrawColor(200, 200, 200);
    doc.line(20, 55, 190, 55);

    doc.setTextColor(0, 0, 0);
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text("Project Quote", 20, 70);

    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    doc.text(`Project: ${data.projectName || "Untitled Project"}`, 20, 80);
    doc.text(`Client: ${data.clientName || "Valued Client"}`, 20, 88);

    // --- Specs Table ---
    const tableHeaderColor: [number, number, number] = [30, 41, 59];
    const costHeaderColor: [number, number, number] = [217, 119, 6];

    let specsBody: string[][] = [
        ["Total Length", `${data.specs.length} m`],
        ["Total Width", `${data.specs.width} m`],
        ["Total Area", `${data.results.area} m²`]
    ];

    if (data.specs.layers && data.specs.layers.length > 0) {
        data.specs.layers.forEach((layer, index) => {
            specsBody.push([`Layer ${index + 1}: ${layer.name || 'Custom'}`, `Thickness: ${layer.thickness}cm | Density: ${layer.density}t/m³ | Tonnage: ${layer.tonnage}t`]);
        });
    }

    autoTable(doc, {
        startY: 100,
        head: [["Specification", "Value"]],
        body: specsBody,
        theme: "striped",
        headStyles: { fillColor: tableHeaderColor, textColor: 255, fontStyle: 'bold' },
        styles: { fontSize: 10, cellPadding: 5 },
        columnStyles: { 0: { fontStyle: 'bold', cellWidth: 50 } },
        margin: { left: 20 },
        tableWidth: 170,
    });

    // --- Cost Table ---
    const costBody = [
        ["Total Required Tonnage", `${data.results.tonnage} t`],
        ["Price per Ton", `${data.language === 'de' ? '€' : '$'}${data.results.pricePerTon || "0.00"}`],
        ["TOTAL ESTIMATE", `${data.language === 'de' ? '€' : '$'}${data.results.totalCost}`],
    ];

    const currentY = (doc as any).lastAutoTable.finalY + 15;

    autoTable(doc, {
        startY: currentY,
        head: [["Cost Breakdown", "Amount"]],
        body: costBody,
        theme: "grid",
        headStyles: { fillColor: costHeaderColor, textColor: 255, fontStyle: 'bold' },
        styles: { fontSize: 10, cellPadding: 5 },
        columnStyles: { 0: { fontStyle: "bold" }, 1: { halign: 'right' } },
        margin: { left: 110 },
        tableWidth: 80,
    });

    // --- Signature ---
    let signatureY = (doc as any).lastAutoTable.finalY + 20;

    if (data.signatureData) {
        doc.setFontSize(12);
        doc.setFont("helvetica", "bold");
        doc.text("Authorized Signature:", 20, signatureY);
        // Image parameters: string, format, x, y, width, height
        doc.addImage(data.signatureData, "PNG", 20, signatureY + 5, 50, 20);

        doc.setDrawColor(0, 0, 0);
        doc.line(20, signatureY + 30, 80, signatureY + 30);
    }

    // --- Footer ---
    const pageHeight = doc.internal.pageSize.height;

    doc.setFillColor(245, 245, 245);
    doc.rect(0, pageHeight - 30, 210, 30, "F");

    doc.setFontSize(8);
    doc.setTextColor(100, 100, 100);
    doc.text("Generated by Smart Field App | Created by Mehdi Lakhouane", 20, pageHeight - 15);
    doc.text("This is an estimate only. Final requirements may vary based on site conditions.", 20, pageHeight - 10);

    const filename = `Quote_${data.projectName.replace(/\s+/g, "_") || "Asphalt_Project"}.pdf`;
    doc.save(filename);
}
