import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { CURRENCY_SYMBOLS, type Currency, type CompanyProfile } from "../store";

interface QuoteData {
    projectName: string;
    clientName: string;
    date: string;
    signatureData?: string;
    documentType?: 'quote' | 'invoice';
    invoiceNumber?: string;
    company?: CompanyProfile;
    currency?: Currency;
    wastePercent?: number;
    specs: {
        length: string;
        width: string;
        layers: any[];
    };
    language?: 'en' | 'de';
    results: {
        area: string;
        tonnage: number;      // gross, incl. waste
        netTonnage?: number;  // theoretical, before waste
        pricePerTon: number;
        totalCost: number;
    };
}

export const GERMAN_VAT_RATE = 0.19;

const LABELS = {
    de: {
        quoteTitle: "Angebot",
        invoiceTitle: "Rechnung",
        subtitle: "Professioneller Asphaltrechner",
        date: "Datum",
        invoiceNo: "Rechnungsnr.",
        serviceDate: "Leistungsdatum",
        project: "Projekt",
        client: "Kunde",
        untitledProject: "Unbenanntes Projekt",
        valuedClient: "Kunde",
        specification: "Spezifikation",
        value: "Wert",
        totalLength: "Gesamtlänge",
        totalWidth: "Gesamtbreite",
        totalArea: "Gesamtfläche",
        layer: "Schicht",
        custom: "Individuell",
        thickness: "Dicke",
        density: "Dichte",
        tonnage: "Menge",
        costOverview: "Kostenübersicht",
        amount: "Betrag",
        netTonnage: "Theoretischer Bedarf",
        waste: "Verschnittzuschlag",
        totalTonnage: "Gesamtbedarf",
        pricePerTon: "Preis pro Tonne",
        subtotal: "Zwischensumme (Netto)",
        vat: "MwSt.",
        grandTotal: "GESAMTBETRAG (Brutto)",
        signature: "Rechtsverbindliche Unterschrift",
        paymentTerms: "Zahlungsbedingungen",
        taxId: "Steuernr./USt-IdNr.",
        estimateNote: "Unverbindliche Schätzung. Der tatsächliche Bedarf kann je nach Baustellenbedingungen abweichen.",
        generatedBy: "Erstellt mit Smart Field | Mehdi Lakhouane",
    },
    en: {
        quoteTitle: "Project Quote",
        invoiceTitle: "Invoice",
        subtitle: "Professional Asphalt Calculator",
        date: "Date",
        invoiceNo: "Invoice No.",
        serviceDate: "Service Date",
        project: "Project",
        client: "Client",
        untitledProject: "Untitled Project",
        valuedClient: "Valued Client",
        specification: "Specification",
        value: "Value",
        totalLength: "Total Length",
        totalWidth: "Total Width",
        totalArea: "Total Area",
        layer: "Layer",
        custom: "Custom",
        thickness: "Thickness",
        density: "Density",
        tonnage: "Tonnage",
        costOverview: "Cost Breakdown",
        amount: "Amount",
        netTonnage: "Theoretical Requirement",
        waste: "Waste Allowance",
        totalTonnage: "Total Required Tonnage",
        pricePerTon: "Price per Ton",
        subtotal: "Subtotal (Net)",
        vat: "VAT",
        grandTotal: "TOTAL",
        signature: "Authorized Signature",
        paymentTerms: "Payment Terms",
        taxId: "Tax ID / VAT ID",
        estimateNote: "This is an estimate only. Final requirements may vary based on site conditions.",
        generatedBy: "Generated by Smart Field | Mehdi Lakhouane",
    },
};

export function generateQuote(data: QuoteData) {
    const doc = new jsPDF();
    const isGerman = data.language === 'de';
    const L = isGerman ? LABELS.de : LABELS.en;
    const isInvoice = data.documentType === 'invoice';
    const locale = isGerman ? 'de-DE' : 'en-US';
    const currency = data.currency ?? (isGerman ? 'EUR' : 'USD');
    const symbol = CURRENCY_SYMBOLS[currency];

    const money = (amount: number) => {
        const formatted = amount.toLocaleString(locale, {
            minimumFractionDigits: 2,
            maximumFractionDigits: 2,
        });
        // German convention places the symbol after the amount
        return isGerman ? `${formatted} ${symbol}` : `${symbol}${formatted}`;
    };
    const num = (value: number, digits = 2) =>
        value.toLocaleString(locale, { minimumFractionDigits: 0, maximumFractionDigits: digits });

    // --- Branding / Header ---
    doc.setFillColor(245, 158, 11); // Amber-500
    doc.rect(0, 0, 210, 45, "F");

    doc.setTextColor(0, 0, 0);
    doc.setFontSize(28);
    doc.setFont("helvetica", "bold");
    doc.text(data.company?.name || "Smart Field", 20, 22);

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(0, 0, 0);
    doc.text(`${L.date}: ${data.date}`, 150, 22);
    if (isInvoice && data.invoiceNumber) {
        doc.text(`${L.invoiceNo}: ${data.invoiceNumber}`, 150, 28);
    }

    doc.setFontSize(12);
    doc.text(L.subtitle, 20, 30);

    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(50, 50, 50);
    doc.text(data.company?.address || "Made by Mehdi Lakhouane", 20, 38);

    // --- Issuer details (required for a compliant invoice) ---
    let infoY = 55;
    if (isInvoice && data.company) {
        doc.setFontSize(8);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(90, 90, 90);
        const issuerLines = [
            data.company.contact,
            data.company.taxId ? `${L.taxId}: ${data.company.taxId}` : '',
        ].filter(Boolean);
        issuerLines.forEach((line) => {
            doc.text(line, 20, infoY);
            infoY += 5;
        });
        infoY += 2;
    }

    doc.setDrawColor(200, 200, 200);
    doc.line(20, infoY, 190, infoY);

    doc.setTextColor(0, 0, 0);
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text(isInvoice ? L.invoiceTitle : L.quoteTitle, 20, infoY + 15);

    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    doc.text(`${L.project}: ${data.projectName || L.untitledProject}`, 20, infoY + 25);
    doc.text(`${L.client}: ${data.clientName || L.valuedClient}`, 20, infoY + 33);
    if (isInvoice) {
        doc.text(`${L.serviceDate}: ${data.date}`, 20, infoY + 41);
    }

    // --- Specs Table ---
    const tableHeaderColor: [number, number, number] = [30, 41, 59];
    const costHeaderColor: [number, number, number] = [217, 119, 6];

    const specsBody: string[][] = [
        [L.totalLength, `${data.specs.length} m`],
        [L.totalWidth, `${data.specs.width} m`],
        [L.totalArea, `${data.results.area} m²`]
    ];

    if (data.specs.layers && data.specs.layers.length > 0) {
        data.specs.layers.forEach((layer, index) => {
            specsBody.push([
                layer.name || `${L.layer} ${index + 1}`,
                `${L.thickness}: ${layer.thickness}cm | ${L.density}: ${layer.density}t/m³ | ${L.tonnage}: ${layer.tonnage}t`
            ]);
        });
    }

    autoTable(doc, {
        startY: infoY + (isInvoice ? 50 : 45),
        head: [[L.specification, L.value]],
        body: specsBody,
        theme: "striped",
        headStyles: { fillColor: tableHeaderColor, textColor: 255, fontStyle: 'bold' },
        styles: { fontSize: 10, cellPadding: 5 },
        columnStyles: { 0: { fontStyle: 'bold', cellWidth: 50 } },
        margin: { left: 20 },
        tableWidth: 170,
    });

    // --- Cost Table ---
    const netTotal = data.results.totalCost;
    const waste = data.wastePercent ?? 0;

    const costBody: string[][] = [];
    if (waste > 0 && data.results.netTonnage) {
        costBody.push([L.netTonnage, `${num(data.results.netTonnage)} t`]);
        costBody.push([`${L.waste} (${num(waste, 1)} %)`, `+ ${num(data.results.tonnage - data.results.netTonnage)} t`]);
    }
    costBody.push([L.totalTonnage, `${num(data.results.tonnage)} t`]);
    costBody.push([L.pricePerTon, money(data.results.pricePerTon)]);

    if (isGerman) {
        costBody.push([L.subtotal, money(netTotal)]);
        costBody.push([`${L.vat} (${GERMAN_VAT_RATE * 100} %)`, money(netTotal * GERMAN_VAT_RATE)]);
        costBody.push([L.grandTotal, money(netTotal * (1 + GERMAN_VAT_RATE))]);
    } else {
        costBody.push([L.grandTotal, money(netTotal)]);
    }

    const currentY = (doc as any).lastAutoTable.finalY + 15;

    autoTable(doc, {
        startY: currentY,
        head: [[L.costOverview, L.amount]],
        body: costBody,
        theme: "grid",
        headStyles: { fillColor: costHeaderColor, textColor: 255, fontStyle: 'bold' },
        styles: { fontSize: 10, cellPadding: 5 },
        columnStyles: { 0: { fontStyle: "bold" }, 1: { halign: 'right' } },
        margin: { left: 110 },
        tableWidth: 80,
    });

    // --- Payment terms (invoice only) ---
    let blockY = (doc as any).lastAutoTable.finalY + 12;
    const pageHeight = doc.internal.pageSize.height;

    if (isInvoice && data.company?.paymentTerms) {
        doc.setFontSize(9);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(0, 0, 0);
        doc.text(`${L.paymentTerms}:`, 20, blockY);
        doc.setFont("helvetica", "normal");
        const terms = doc.splitTextToSize(data.company.paymentTerms, 170) as string[];
        doc.text(terms, 20, blockY + 5);
        blockY += 5 + terms.length * 5 + 8;
    }

    // --- Signature ---
    if (data.signatureData) {
        // Start a new page if the signature block would collide with the footer
        if (blockY + 40 > pageHeight - 35) {
            doc.addPage();
            blockY = 30;
        }
        doc.setFontSize(12);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(0, 0, 0);
        doc.text(`${L.signature}:`, 20, blockY);
        doc.addImage(data.signatureData, "PNG", 20, blockY + 5, 50, 20);

        doc.setDrawColor(0, 0, 0);
        doc.line(20, blockY + 30, 80, blockY + 30);
    }

    // --- Footer ---
    doc.setFillColor(245, 245, 245);
    doc.rect(0, pageHeight - 30, 210, 30, "F");

    doc.setFontSize(8);
    doc.setTextColor(100, 100, 100);
    doc.text(L.generatedBy, 20, pageHeight - 15);
    if (!isInvoice) {
        doc.text(L.estimateNote, 20, pageHeight - 10);
    } else if (data.company?.taxId) {
        doc.text(`${L.taxId}: ${data.company.taxId}`, 20, pageHeight - 10);
    }

    const docLabel = isInvoice ? (isGerman ? 'Rechnung' : 'Invoice') : (isGerman ? 'Angebot' : 'Quote');
    const filename = `${docLabel}_${data.projectName.replace(/\s+/g, "_") || "Asphalt_Project"}.pdf`;
    doc.save(filename);
}
