"use client";

import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { Button } from "@/components/ui/Button";
import { FileCheck } from "lucide-react";
import { useLanguage } from "@/contexts/LanguageContext";
import { useStore, CURRENCY_SYMBOLS } from "@/lib/store";
import { parseLocaleNumber } from "@/lib/calculations";

const REPORT_LABELS = {
    de: {
        title: "Smart Field: Einbauprotokoll",
        report: "Bericht",
        date: "Datum",
        projectDetails: "Projektdaten",
        projectName: "Projektname",
        client: "Auftraggeber",
        site: "Baustelle",
        requirements: "Berechneter Bedarf",
        total: "Gesamt",
        materialCost: "Materialkosten (geschätzt)",
        totalLayers: "Anzahl Schichten",
        signatureManager: "Unterschrift Bauleiter",
        signatureClient: "Unterschrift Auftraggeber",
        footer: "Erstellt mit Smart Field - Der professionelle Asphalt-Assistent",
        filename: "Einbauprotokoll",
        draft: "Entwurf",
    },
    en: {
        title: "Smart Field: Placement Report",
        report: "Report",
        date: "Date",
        projectDetails: "Project Details",
        projectName: "Project Name",
        client: "Client / Contractor",
        site: "Construction Site",
        requirements: "Calculated Requirements",
        total: "Total",
        materialCost: "Est. Material Cost",
        totalLayers: "Total Layers",
        signatureManager: "Signature Site Manager",
        signatureClient: "Signature Client",
        footer: "Generated by Smart Field - The Professional Asphalt Assistant",
        filename: "Placement_Report",
        draft: "Draft",
    },
};

export default function PDFReportButton() {
    const { t, language } = useLanguage();
    // Get all necessary data from the store
    const store = useStore();

    const generatePDF = () => {
        const isGerman = language === 'de';
        const L = isGerman ? REPORT_LABELS.de : REPORT_LABELS.en;
        const locale = isGerman ? 'de-DE' : 'en-US';
        const symbol = CURRENCY_SYMBOLS[store.currency];
        const money = (amount: number) => {
            const formatted = amount.toLocaleString(locale, { minimumFractionDigits: 2, maximumFractionDigits: 2 });
            return isGerman ? `${formatted} ${symbol}` : `${symbol}${formatted}`;
        };

        const totalThickness = store.layers.reduce((sum, layer) => sum + parseLocaleNumber(layer.thickness), 0).toString();
        const primaryDensity = store.layers[0]?.density || '2.4';

        const doc = new jsPDF();

        // --- Header ---
        doc.setFontSize(22);
        doc.setTextColor(255, 165, 0); // Primary Orange/Yellow
        doc.text(L.title, 14, 20);

        doc.setFontSize(10);
        doc.setTextColor(100);
        doc.text(`${t('title') || 'Asphalt Calculator'} ${L.report}`, 14, 26);
        doc.text(`${L.date}: ${new Date().toLocaleDateString(locale)}`, 14, 32);

        // --- Project Info ---
        autoTable(doc, {
            startY: 40,
            head: [[L.projectDetails, '']],
            body: [
                [L.projectName, store.projectName || '—'],
                [L.client, store.clientName || '—'],
                [L.site, '—'], // Placeholder for manual entry
            ],
            theme: 'grid',
            headStyles: { fillColor: [66, 66, 66] },
        });

        // --- Technical Specs ---
        autoTable(doc, {
            startY: (doc as any).lastAutoTable?.finalY ? (doc as any).lastAutoTable.finalY + 10 : 40,
            head: [[t('dimensions') || 'Dimensions & Specs', 'Value']],
            body: [
                [`${t('length')} (${t('units.length')})`, store.length],
                [`${t('width')} (${t('units.length')})`, store.width],
                [`${t('thickness')} (${t('units.thickness')})`, totalThickness],
                [`${t('density')} (${t('units.density')})`, primaryDensity],
                [`${t('area')} (${t('units.area')})`, store.area.toFixed(2)],
            ],
            theme: 'striped',
            headStyles: { fillColor: [255, 165, 0], textColor: [0, 0, 0] },
        });

        // --- Results ---
        autoTable(doc, {
            startY: (doc as any).lastAutoTable?.finalY ? (doc as any).lastAutoTable.finalY + 10 : 40,
            head: [[L.requirements, L.total]],
            body: [
                [{ content: `${t('tonnage')} (${t('units.tonnage')})`, styles: { fontStyle: 'bold' } }, { content: store.tonnage.toString(), styles: { fontStyle: 'bold', textColor: [255, 0, 0] } }],
                [L.materialCost, store.totalCost > 0 ? money(store.totalCost) : '—'],
                [L.totalLayers, store.layers.length.toString()],
            ],
            theme: 'grid',
            headStyles: { fillColor: [66, 66, 66] },
        });

        // --- Signatures ---
        const finalY = (doc as any).lastAutoTable.finalY + 30;

        doc.setFontSize(10);
        doc.setTextColor(0);
        doc.text("__________________________", 14, finalY);
        doc.text(L.signatureManager, 14, finalY + 5);

        doc.text("__________________________", 110, finalY);
        doc.text(L.signatureClient, 110, finalY + 5);

        // --- Footer ---
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text(L.footer, 14, 285);

        doc.save(`${L.filename}_${store.projectName || L.draft}.pdf`);
    };

    return (
        <Button
            onClick={generatePDF}
            className="w-full bg-gradient-to-r from-orange-500 to-amber-500 hover:from-orange-600 hover:to-amber-600 text-white shadow-lg space-x-2"
        >
            <FileCheck className="w-4 h-4" />
            <span>{t('downloadReport') || 'Download PDF Report'}</span>
        </Button>
    );
}
