"use client";

import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { Button } from "@/components/ui/Button";
import { FileCheck } from "lucide-react";
import { useLanguage } from "@/contexts/LanguageContext";
import { useStore } from "@/lib/store";

export default function PDFReportButton() {
    const { t } = useLanguage();
    // Get all necessary data from the store
    const store = useStore();

    const generatePDF = () => {
        const doc = new jsPDF();

        // --- Header ---
        doc.setFontSize(22);
        doc.setTextColor(255, 165, 0); // Primary Orange/Yellow
        doc.text("Smart Field: Einbauprotokoll", 14, 20);

        doc.setFontSize(10);
        doc.setTextColor(100);
        doc.text(`${t('title') || 'Asphalt Calculator'} Report`, 14, 26);
        doc.text(`Date: ${new Date().toLocaleDateString()}`, 14, 32);

        // --- Project Info ---
        autoTable(doc, {
            startY: 40,
            head: [[t('projectDetails') || 'Project Details', '']],
            body: [
                ['Project Name', store.projectName || '—'],
                ['Client / Contractor', store.clientName || '—'],
                ['Construction Site', '—'], // Placeholder for manual entry
            ],
            theme: 'grid',
            headStyles: { fillColor: [66, 66, 66] },
        });

        // --- Technical Specs ---
        autoTable(doc, {
            startY: (doc as any).lastAutoTable?.finalY ? (doc as any).lastAutoTable.finalY + 10 : 40,
            head: [[t('dimensions') || 'Dimensions & Specs', 'Value']],
            body: [
                [`${t('length')} (${t('units.length')})`, store.length],
                [`${t('width')} (${t('units.length')})`, store.width],
                [`${t('thickness')} (${t('units.thickness')})`, store.thickness],
                [`${t('density')} (${t('units.density')})`, store.density],
                [`${t('area')} (${t('units.area')})`, store.area.toFixed(2)],
            ],
            theme: 'striped',
            headStyles: { fillColor: [255, 165, 0], textColor: [0, 0, 0] },
        });

        // --- Results ---
        autoTable(doc, {
            startY: (doc as any).lastAutoTable?.finalY ? (doc as any).lastAutoTable.finalY + 10 : 40,
            head: [[t('summary') || 'Calculated Requirements', 'Total']],
            body: [
                [{ content: `${t('tonnage')} (${t('units.tonnage')})`, styles: { fontStyle: 'bold' } }, { content: store.tonnage.toString(), styles: { fontStyle: 'bold', textColor: [255, 0, 0] } }],
                ['Est. Material Cost', store.totalCost > 0 ? `${store.totalCost.toFixed(2)} €` : '—'],
                ['Compaction Factor', store.isLoose ? 'Loose (Unverdichtet)' : 'Compacted (Verdichtet)'],
            ],
            theme: 'grid',
            headStyles: { fillColor: [66, 66, 66] },
        });

        // --- Signatures ---
        const finalY = (doc as any).lastAutoTable.finalY + 30;

        doc.setFontSize(10);
        doc.setTextColor(0);
        doc.text("__________________________", 14, finalY);
        doc.text("Signature Site Manager", 14, finalY + 5);

        doc.text("__________________________", 110, finalY);
        doc.text("Signature Client", 110, finalY + 5);

        // --- Footer ---
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text("Generated by Smart Field - The Professional Asphalt Assistant", 14, 285);

        doc.save(`Einbauprotokoll_${store.projectName || 'Draft'}.pdf`);
    };

    return (
        <Button
            onClick={generatePDF}
            className="w-full bg-gradient-to-r from-orange-500 to-amber-500 hover:from-orange-600 hover:to-amber-600 text-white shadow-lg space-x-2"
        >
            <FileCheck className="w-4 h-4" />
            <span>{t('downloadReport') || 'Download PDF Report'}</span>
        </Button>
    );
}
