import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

interface QuoteData {
    projectName: string;
    clientName: string;
    date: string;
    specs: {
        length: string;
        width: string;
        thickness: string;
        density: string;
        materialType?: string;
        pricePerTon?: string;
    };
    language?: 'en' | 'de';
    results: {
        area: string;
        tonnage: number;
        pricePerTon: string;
        totalCost: string;
    };
}

export function generateQuote(data: QuoteData) {
    const doc = new jsPDF();

    // --- Branding / Header ---
    // Background accent - Amber Gradient effect (simulated with rects)
    doc.setFillColor(245, 158, 11); // Amber-500
    doc.rect(0, 0, 210, 45, "F");

    // Title
    doc.setTextColor(0, 0, 0); // Black text
    doc.setFontSize(28);
    doc.setFont("helvetica", "bold");
    doc.text("Smart Field", 20, 22);

    // Credit - Next to Title (User Request)
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold"); // Bold for credit
    doc.setTextColor(50, 50, 50); // Slightly softer black
    doc.text("Made by Mehdi Lakhouane", 20, 38);

    // Date in Header (Right aligned)
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(0, 0, 0);
    doc.text(`Date: ${data.date}`, 150, 22);

    // Subtitle / App Description
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.text("Professional Asphalt Calculator", 20, 30);

    // --- Client / Project Info ---
    // Separator Line
    doc.setDrawColor(200, 200, 200);
    doc.line(20, 55, 190, 55);

    doc.setTextColor(0, 0, 0);
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text("Project Quote", 20, 70);

    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    doc.text(`Project: ${data.projectName || "Untitled Project"}`, 20, 80);
    doc.text(`Client: ${data.clientName || "Valued Client"}`, 20, 88);

    // --- Specs Table ---
    // Enhanced styles
    const tableHeaderColor: [number, number, number] = [30, 41, 59]; // Slate-800
    const costHeaderColor: [number, number, number] = [217, 119, 6]; // Amber-600

    const specsBody = [
        ["Length", `${data.specs.length} m`],
        ["Width", `${data.specs.width} m`],
        ["Thickness", `${data.specs.thickness} cm`],
        ["Density", `${data.specs.density} t/m³`],
        ...(data.specs.materialType ? [["Material Type", data.specs.materialType]] : []),
        ["Total Area", `${data.results.area} m²`],
    ];

    autoTable(doc, {
        startY: 100,
        head: [["Specification", "Value"]],
        body: specsBody,
        theme: "striped",
        headStyles: { fillColor: tableHeaderColor, textColor: 255, fontStyle: 'bold' },
        styles: { fontSize: 10, cellPadding: 5 },
        columnStyles: { 0: { fontStyle: 'bold', cellWidth: 40 } },
        margin: { left: 20 },
        tableWidth: 80,
    });

    // --- Cost Table ---
    const costBody = [
        ["Required Tonnage", `${data.results.tonnage} t`],
        ["Price per Ton", `${data.language === 'de' ? '€' : '$'}${data.specs.pricePerTon || "0.00"}`],
        ["TOTAL ESTIMATE", `${data.language === 'de' ? '€' : '$'}${data.results.totalCost}`],
    ];

    autoTable(doc, {
        startY: 100,
        head: [["Cost Breakdown", "Amount"]],
        body: costBody,
        theme: "grid",
        headStyles: { fillColor: costHeaderColor, textColor: 255, fontStyle: 'bold' },
        styles: { fontSize: 10, cellPadding: 5 },
        columnStyles: { 0: { fontStyle: "bold" }, 1: { halign: 'right' } },
        margin: { left: 110 },
        tableWidth: 80,
    });

    // --- Footer ---
    const pageHeight = doc.internal.pageSize.height;

    // Footer Background
    doc.setFillColor(245, 245, 245);
    doc.rect(0, pageHeight - 30, 210, 30, "F");

    doc.setFontSize(8);
    doc.setTextColor(100, 100, 100);
    doc.text("Generated by Smart Field App | Created by Mehdi Lakhouane", 20, pageHeight - 15);
    doc.text("This is an estimate only. Final requirements may vary based on site conditions.", 20, pageHeight - 10);

    // Trigger Download
    const filename = `Quote_${data.projectName.replace(/\s+/g, "_") || "Asphalt_Project"}.pdf`;
    doc.save(filename);
}
