import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

interface QuoteData {
    projectName: string;
    clientName: string;
    date: string;
    specs: {
        length: string;
        width: string;
        thickness: string;
        density: string;
        pricePerTon?: string;
    };
    results: {
        area: string;
        tonnage: number;
        pricePerTon: string;
        totalCost: string;
    };
}

export function generateQuote(data: QuoteData) {
    const doc = new jsPDF();

    // --- Branding / Header ---
    // Background accent
    doc.setFillColor(234, 179, 8); // Amber-500 equivalent
    doc.rect(0, 0, 210, 40, "F");

    // Title
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(26);
    doc.setFont("helvetica", "bold");
    doc.text("Smart Field", 20, 20);

    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");
    doc.text("Professional Asphalt Calculator", 20, 28);

    // --- Client / Project Info ---
    doc.setTextColor(50, 50, 50);
    doc.setFontSize(10);
    doc.text(`Date: ${data.date}`, 150, 20);

    doc.setTextColor(0, 0, 0);
    doc.setFontSize(14);
    doc.text("Project Quote", 20, 60);

    doc.setFontSize(11);
    doc.text(`Project: ${data.projectName || "Untitled Project"}`, 20, 70);
    doc.text(`Client: ${data.clientName || "Valued Client"}`, 20, 78);

    // --- Specs Table ---
    const specsBody = [
        ["Length", `${data.specs.length} m`],
        ["Width", `${data.specs.width} m`],
        ["Thickness", `${data.specs.thickness} cm`],
        ["Density", `${data.specs.density} t/m³`],
        ["Total Area", `${data.results.area} m²`],
    ];

    autoTable(doc, {
        startY: 90,
        head: [["Specification", "Value"]],
        body: specsBody,
        theme: "striped",
        headStyles: { fillColor: [50, 50, 50] },
        styles: { fontSize: 10 },
        margin: { left: 20 },
        tableWidth: 80,
    });

    // --- Cost Table ---
    // We place this next to the specs table if possible, or below
    const costBody = [
        ["Required Tonnage", `${data.results.tonnage} t`],
        ["Price per Ton", `$${data.specs.pricePerTon || "0.00"}`],
        ["TOTAL ESTIMATE", `$${data.results.totalCost}`],
    ];

    autoTable(doc, {
        startY: 90,
        head: [["Cost Breakdown", "Amount"]],
        body: costBody,
        theme: "grid",
        headStyles: { fillColor: [234, 179, 8], textColor: [0, 0, 0] },
        columnStyles: { 0: { fontStyle: "bold" } },
        margin: { left: 110 },
        tableWidth: 80,
    });

    // --- Footer ---
    const pageHeight = doc.internal.pageSize.height;
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text("Generated by Smart Field App", 20, pageHeight - 10);
    doc.text("This is an estimate only. Final requirements may vary based on site conditions.", 20, pageHeight - 15);

    // Trigger Download
    const filename = `Quote_${data.projectName.replace(/\s+/g, "_") || "Asphalt_Project"}.pdf`;
    doc.save(filename);
}
